// What each kernel takes, in order, and which of its arguments size the
// block; and, unless ``BLOCHSIM_TABLE_ONLY``, the kernels themselves with a
// call that unpacks a launch's arguments into each.
#pragma once

#include <cstdint>

#include "_lanes.hpp"
#include "_tile.hpp"
#ifndef BLOCHSIM_TABLE_ONLY
namespace epg {
#include "_epg_kernels.hpp"
}  // namespace epg
namespace pools {
#include "_pools_kernels.hpp"
}  // namespace pools
namespace perk {
#include "_perk_kernels.hpp"
}  // namespace perk
#endif

namespace bsk {

// One argument as the launcher receives it from Python.
union Arg {
    void* p;
    std::int64_t i;
    double f;
};

constexpr int MAX_ARGUMENTS = 128;

struct Arguments {
    Arg a[MAX_ARGUMENTS];
};

struct KernelInfo {
    const char* name;
    // Comma-separated parameter names, in order.
    const char* params;
    // One letter per parameter: p a pointer, i an integer, f a float.
    const char* kinds;
    // The parameters whose values are the block's width along x and y, or
    // -1 where the program has no such axis.
    int x;
    int y;
    // The parameter whose value is the length of z, or -1.
    int z;
    // Rows of y each thread holds on a card.
    int lanes;
};

#ifndef BLOCHSIM_TABLE_ONLY
BSK_HD void call_three_pool_table_jvp_kernel(const Arg* a) {
    epg::_three_pool_table_jvp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<std::int32_t*>(a[15].p),
        static_cast<float*>(a[16].p),
        a[17].i,
        a[18].i,
        a[19].i);
}

BSK_HD void call_three_pool_table_kernel(const Arg* a) {
    epg::_three_pool_table_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<std::int32_t*>(a[8].p),
        static_cast<float*>(a[9].p),
        a[10].i,
        a[11].i,
        a[12].i);
}

BSK_HD void call_epg_vjp_kernel(const Arg* a) {
    epg::_epg_vjp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::int32_t*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<std::uint8_t*>(a[21].p),
        static_cast<std::int32_t*>(a[22].p),
        static_cast<std::int32_t*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<std::int32_t*>(a[28].p),
        static_cast<float*>(a[29].p),
        static_cast<std::int32_t*>(a[30].p),
        static_cast<std::int32_t*>(a[31].p),
        static_cast<float*>(a[32].p),
        static_cast<float*>(a[33].p),
        static_cast<float*>(a[34].p),
        a[35].i,
        static_cast<float*>(a[36].p),
        static_cast<float*>(a[37].p),
        static_cast<float*>(a[38].p),
        static_cast<float*>(a[39].p),
        static_cast<float*>(a[40].p),
        static_cast<float*>(a[41].p),
        static_cast<float*>(a[42].p),
        static_cast<float*>(a[43].p),
        static_cast<float*>(a[44].p),
        a[45].i,
        a[46].i,
        a[47].i,
        a[48].i,
        a[49].i,
        a[50].i,
        static_cast<float>(a[51].f),
        static_cast<float>(a[52].f),
        a[53].i,
        static_cast<float>(a[54].f),
        static_cast<float>(a[55].f),
        a[56].i,
        a[57].i,
        a[58].i,
        a[59].i,
        a[60].i,
        a[61].i,
        a[62].i,
        a[63].i,
        a[64].i,
        a[65].i,
        a[66].i,
        a[67].i,
        a[68].i,
        a[69].i,
        a[70].i,
        a[71].i,
        a[72].i,
        a[73].i,
        a[74].i,
        a[75].i,
        a[76].i,
        a[77].i);
}

BSK_HD void call_epg_vjp_jvp_kernel(const Arg* a) {
    epg::_epg_vjp_jvp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::int32_t*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<std::uint8_t*>(a[21].p),
        static_cast<std::int32_t*>(a[22].p),
        static_cast<std::int32_t*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<std::int32_t*>(a[27].p),
        static_cast<float*>(a[28].p),
        static_cast<float*>(a[29].p),
        static_cast<std::int32_t*>(a[30].p),
        static_cast<float*>(a[31].p),
        static_cast<float*>(a[32].p),
        static_cast<float*>(a[33].p),
        static_cast<float*>(a[34].p),
        static_cast<float*>(a[35].p),
        static_cast<float*>(a[36].p),
        static_cast<float*>(a[37].p),
        static_cast<float*>(a[38].p),
        static_cast<float*>(a[39].p),
        static_cast<float*>(a[40].p),
        static_cast<float*>(a[41].p),
        static_cast<float*>(a[42].p),
        static_cast<float*>(a[43].p),
        static_cast<float*>(a[44].p),
        static_cast<float*>(a[45].p),
        static_cast<float*>(a[46].p),
        static_cast<float*>(a[47].p),
        static_cast<float*>(a[48].p),
        static_cast<float*>(a[49].p),
        static_cast<float*>(a[50].p),
        static_cast<float*>(a[51].p),
        static_cast<float*>(a[52].p),
        static_cast<float*>(a[53].p),
        static_cast<std::int32_t*>(a[54].p),
        static_cast<float*>(a[55].p),
        static_cast<float*>(a[56].p),
        static_cast<float*>(a[57].p),
        a[58].i,
        static_cast<float*>(a[59].p),
        static_cast<float*>(a[60].p),
        static_cast<float*>(a[61].p),
        static_cast<float*>(a[62].p),
        static_cast<float*>(a[63].p),
        static_cast<float*>(a[64].p),
        static_cast<float*>(a[65].p),
        static_cast<float*>(a[66].p),
        static_cast<float*>(a[67].p),
        static_cast<float*>(a[68].p),
        static_cast<float*>(a[69].p),
        static_cast<float*>(a[70].p),
        static_cast<float*>(a[71].p),
        static_cast<float*>(a[72].p),
        a[73].i,
        a[74].i,
        a[75].i,
        a[76].i,
        a[77].i,
        a[78].i,
        static_cast<float>(a[79].f),
        static_cast<float>(a[80].f),
        static_cast<float>(a[81].f),
        static_cast<float>(a[82].f),
        a[83].i,
        a[84].i,
        a[85].i,
        a[86].i,
        a[87].i,
        a[88].i,
        a[89].i,
        a[90].i,
        a[91].i,
        a[92].i,
        a[93].i,
        a[94].i,
        a[95].i,
        a[96].i,
        a[97].i,
        a[98].i,
        a[99].i,
        a[100].i,
        a[101].i,
        a[102].i,
        a[103].i,
        a[104].i,
        a[105].i,
        a[106].i);
}

BSK_HD void call_epg_real_vjp_jvp_kernel(const Arg* a) {
    epg::_epg_real_vjp_jvp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<std::int32_t*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<std::uint8_t*>(a[9].p),
        static_cast<std::int32_t*>(a[10].p),
        static_cast<std::int32_t*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<float*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<float*>(a[21].p),
        static_cast<float*>(a[22].p),
        static_cast<float*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<float*>(a[28].p),
        a[29].i,
        a[30].i,
        a[31].i,
        a[32].i,
        a[33].i,
        a[34].i,
        a[35].i,
        a[36].i,
        a[37].i,
        a[38].i,
        a[39].i,
        a[40].i,
        a[41].i,
        a[42].i,
        a[43].i,
        a[44].i,
        a[45].i);
}

BSK_HD void call_epg_real_vjp_kernel(const Arg* a) {
    epg::_epg_real_vjp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<std::int32_t*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<std::uint8_t*>(a[9].p),
        static_cast<std::int32_t*>(a[10].p),
        static_cast<std::int32_t*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        a[17].i,
        a[18].i,
        a[19].i,
        a[20].i,
        a[21].i,
        a[22].i,
        a[23].i,
        a[24].i,
        a[25].i,
        a[26].i,
        a[27].i,
        a[28].i,
        a[29].i,
        a[30].i,
        a[31].i,
        a[32].i,
        a[33].i);
}

BSK_HD void call_epg_real_kernel(const Arg* a) {
    epg::_epg_real_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<std::int32_t*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<std::uint8_t*>(a[9].p),
        static_cast<std::int32_t*>(a[10].p),
        static_cast<std::int32_t*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        a[14].i,
        a[15].i,
        a[16].i,
        a[17].i,
        a[18].i,
        a[19].i,
        a[20].i,
        a[21].i,
        a[22].i,
        a[23].i,
        a[24].i,
        a[25].i,
        a[26].i,
        a[27].i);
}

BSK_HD void call_epg_real_jvp_kernel(const Arg* a) {
    epg::_epg_real_jvp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<std::int32_t*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<std::uint8_t*>(a[9].p),
        static_cast<std::int32_t*>(a[10].p),
        static_cast<std::int32_t*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<float*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<float*>(a[21].p),
        a[22].i,
        a[23].i,
        a[24].i,
        a[25].i,
        a[26].i,
        a[27].i,
        a[28].i,
        a[29].i,
        a[30].i,
        a[31].i,
        a[32].i,
        a[33].i,
        a[34].i,
        a[35].i);
}

BSK_HD void call_epg_kernel(const Arg* a) {
    epg::_epg_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::int32_t*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<float*>(a[21].p),
        static_cast<float*>(a[22].p),
        static_cast<std::uint8_t*>(a[23].p),
        static_cast<std::int32_t*>(a[24].p),
        static_cast<std::int32_t*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<float*>(a[28].p),
        static_cast<std::int32_t*>(a[29].p),
        static_cast<float*>(a[30].p),
        static_cast<float*>(a[31].p),
        static_cast<std::int32_t*>(a[32].p),
        static_cast<std::int32_t*>(a[33].p),
        static_cast<float*>(a[34].p),
        static_cast<float*>(a[35].p),
        static_cast<float*>(a[36].p),
        a[37].i,
        a[38].i,
        a[39].i,
        a[40].i,
        static_cast<float>(a[41].f),
        static_cast<float>(a[42].f),
        static_cast<float>(a[43].f),
        static_cast<float>(a[44].f),
        a[45].i,
        a[46].i,
        a[47].i,
        a[48].i,
        a[49].i,
        a[50].i,
        a[51].i,
        a[52].i,
        a[53].i,
        a[54].i,
        a[55].i,
        a[56].i,
        a[57].i,
        a[58].i,
        a[59].i,
        a[60].i,
        a[61].i,
        a[62].i,
        a[63].i,
        a[64].i,
        a[65].i,
        a[66].i);
}

BSK_HD void call_epg_jvp_kernel(const Arg* a) {
    epg::_epg_jvp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<float*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::int32_t*>(a[18].p),
        static_cast<float*>(a[19].p),
        static_cast<float*>(a[20].p),
        static_cast<std::uint8_t*>(a[21].p),
        static_cast<std::int32_t*>(a[22].p),
        static_cast<std::int32_t*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<float*>(a[28].p),
        static_cast<float*>(a[29].p),
        static_cast<float*>(a[30].p),
        static_cast<float*>(a[31].p),
        static_cast<float*>(a[32].p),
        static_cast<float*>(a[33].p),
        static_cast<float*>(a[34].p),
        static_cast<float*>(a[35].p),
        static_cast<float*>(a[36].p),
        static_cast<float*>(a[37].p),
        static_cast<float*>(a[38].p),
        static_cast<float*>(a[39].p),
        static_cast<float*>(a[40].p),
        static_cast<float*>(a[41].p),
        static_cast<float*>(a[42].p),
        static_cast<float*>(a[43].p),
        static_cast<float*>(a[44].p),
        static_cast<float*>(a[45].p),
        static_cast<float*>(a[46].p),
        static_cast<std::int32_t*>(a[47].p),
        static_cast<float*>(a[48].p),
        static_cast<float*>(a[49].p),
        static_cast<std::int32_t*>(a[50].p),
        static_cast<float*>(a[51].p),
        static_cast<std::int32_t*>(a[52].p),
        static_cast<float*>(a[53].p),
        static_cast<float*>(a[54].p),
        static_cast<float*>(a[55].p),
        a[56].i,
        a[57].i,
        a[58].i,
        a[59].i,
        static_cast<float>(a[60].f),
        static_cast<float>(a[61].f),
        static_cast<float>(a[62].f),
        static_cast<float>(a[63].f),
        a[64].i,
        a[65].i,
        a[66].i,
        a[67].i,
        a[68].i,
        a[69].i,
        a[70].i,
        a[71].i,
        a[72].i,
        a[73].i,
        a[74].i,
        a[75].i,
        a[76].i,
        a[77].i,
        a[78].i,
        a[79].i,
        a[80].i,
        a[81].i,
        a[82].i,
        a[83].i,
        a[84].i,
        a[85].i);
}

BSK_HD void call_pooled_kernel(const Arg* a) {
    pools::_pooled_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<std::int32_t*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::uint8_t*>(a[18].p),
        static_cast<std::int32_t*>(a[19].p),
        static_cast<std::int32_t*>(a[20].p),
        static_cast<float*>(a[21].p),
        static_cast<float*>(a[22].p),
        static_cast<float*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<std::int32_t*>(a[28].p),
        static_cast<float*>(a[29].p),
        static_cast<std::int32_t*>(a[30].p),
        static_cast<float*>(a[31].p),
        static_cast<float*>(a[32].p),
        static_cast<std::int32_t*>(a[33].p),
        static_cast<float*>(a[34].p),
        static_cast<float*>(a[35].p),
        static_cast<float*>(a[36].p),
        static_cast<float*>(a[37].p),
        a[38].i,
        a[39].i,
        a[40].i,
        a[41].i,
        a[42].i,
        a[43].i,
        static_cast<float>(a[44].f),
        static_cast<float>(a[45].f),
        static_cast<float>(a[46].f),
        static_cast<float>(a[47].f),
        a[48].i,
        a[49].i,
        a[50].i,
        a[51].i,
        a[52].i,
        a[53].i,
        a[54].i,
        a[55].i,
        a[56].i,
        a[57].i,
        a[58].i,
        a[59].i,
        a[60].i,
        a[61].i,
        a[62].i,
        a[63].i,
        a[64].i,
        a[65].i,
        a[66].i,
        a[67].i,
        a[68].i,
        a[69].i,
        a[70].i);
}

BSK_HD void call_pooled_adjoint_kernel(const Arg* a) {
    pools::_pooled_adjoint_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        static_cast<float*>(a[7].p),
        static_cast<float*>(a[8].p),
        static_cast<float*>(a[9].p),
        static_cast<float*>(a[10].p),
        static_cast<float*>(a[11].p),
        static_cast<float*>(a[12].p),
        static_cast<float*>(a[13].p),
        static_cast<float*>(a[14].p),
        static_cast<std::int32_t*>(a[15].p),
        static_cast<float*>(a[16].p),
        static_cast<float*>(a[17].p),
        static_cast<std::uint8_t*>(a[18].p),
        static_cast<std::int32_t*>(a[19].p),
        static_cast<std::int32_t*>(a[20].p),
        static_cast<float*>(a[21].p),
        static_cast<float*>(a[22].p),
        static_cast<float*>(a[23].p),
        static_cast<float*>(a[24].p),
        static_cast<float*>(a[25].p),
        static_cast<float*>(a[26].p),
        static_cast<float*>(a[27].p),
        static_cast<std::int32_t*>(a[28].p),
        static_cast<float*>(a[29].p),
        static_cast<std::int32_t*>(a[30].p),
        static_cast<float*>(a[31].p),
        static_cast<float*>(a[32].p),
        static_cast<std::int32_t*>(a[33].p),
        static_cast<float*>(a[34].p),
        static_cast<float*>(a[35].p),
        static_cast<float*>(a[36].p),
        static_cast<float*>(a[37].p),
        static_cast<float*>(a[38].p),
        static_cast<float*>(a[39].p),
        static_cast<float*>(a[40].p),
        static_cast<float*>(a[41].p),
        static_cast<float*>(a[42].p),
        static_cast<float*>(a[43].p),
        static_cast<float*>(a[44].p),
        static_cast<float*>(a[45].p),
        static_cast<float*>(a[46].p),
        static_cast<float*>(a[47].p),
        static_cast<float*>(a[48].p),
        static_cast<float*>(a[49].p),
        a[50].i,
        a[51].i,
        a[52].i,
        a[53].i,
        a[54].i,
        a[55].i,
        static_cast<float>(a[56].f),
        static_cast<float>(a[57].f),
        static_cast<float>(a[58].f),
        static_cast<float>(a[59].f),
        a[60].i,
        a[61].i,
        a[62].i,
        a[63].i,
        a[64].i,
        a[65].i,
        a[66].i,
        a[67].i,
        a[68].i,
        a[69].i,
        a[70].i,
        a[71].i,
        a[72].i,
        a[73].i,
        a[74].i,
        a[75].i,
        a[76].i,
        a[77].i,
        a[78].i,
        a[79].i,
        a[80].i,
        a[81].i,
        a[82].i,
        a[83].i,
        a[84].i,
        a[85].i,
        a[86].i,
        a[87].i,
        a[88].i);
}

BSK_HD void call_regress_kernel(const Arg* a) {
    perk::_regress_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        static_cast<float*>(a[6].p),
        a[7].i,
        a[8].i,
        a[9].i,
        a[10].i,
        static_cast<float>(a[11].f),
        a[12].i,
        a[13].i);
}

BSK_HD void call_regress_vjp_kernel(const Arg* a) {
    perk::_regress_vjp_kernel(
        static_cast<float*>(a[0].p),
        static_cast<float*>(a[1].p),
        static_cast<float*>(a[2].p),
        static_cast<float*>(a[3].p),
        static_cast<float*>(a[4].p),
        static_cast<float*>(a[5].p),
        a[6].i,
        a[7].i,
        a[8].i,
        a[9].i,
        static_cast<float>(a[10].f),
        a[11].i,
        a[12].i);
}

#endif

inline constexpr KernelInfo KERNELS[] = {
    {"_three_pool_table_jvp_kernel", "t1,t1_pool_b,t1_bound,pool_b_exchange,bound_exchange,pool_b_fraction,bound_fraction,d_t1,d_t1_pool_b,d_t1_bound,d_pool_b_exchange,d_bound_exchange,d_pool_b_fraction,d_bound_fraction,durations,rows,table,voxel_count,BLOCK,narrow", "pppppppppppppppppiii", 18, -1, -1, BLOCHSIM_LANES__three_pool_table_jvp_kernel},
    {"_three_pool_table_kernel", "t1,t1_pool_b,t1_bound,pool_b_exchange,bound_exchange,pool_b_fraction,bound_fraction,durations,rows,table,voxel_count,BLOCK,narrow", "ppppppppppiii", 11, -1, -1, BLOCHSIM_LANES__three_pool_table_kernel},
    {"_epg_vjp_kernel", "t1,t2,m0,b1,b1_phase,b0,inversion_efficiency,diffusion,velocity,bound_fraction,exchange_rate,t1_bound,pool_b_fraction,pool_b_exchange,t1_pool_b,t2_pool_b,pool_b_shift,duration,kind,flip,phase,action,output_index,shim_index,saturation,rf_frequency,lineshape,profile,profile_index,pairs,pair_index,duration_row,pool_table,pool_bars,pool_durations,row_count,grad_pair,grad_output_real,grad_output_imag,grad_tissue,grad_flip,grad_phase,grad_duration,trajectory_r,trajectory_i,problem_base,problem_end,atom_count,train_count,event_count,output_count,flow_scale,washout_scale,shim_rows,profile_step,lineshape_step,state_count,single_train,atom_stride,shimmed,locations,profiled,profile_bins,dynamic,broadened,lineshape_bins,pools,narrow,tabulated,off_axis,moving,diffusing,transmit,density,inverting,recording,block_states,problems", "pppppppppppppppppppppppppppppppppppipppppppppiiiiiiffiffiiiiiiiiiiiiiiiiiiiiii", 76, 77, -1, BLOCHSIM_LANES__epg_vjp_kernel},
    {"_epg_vjp_jvp_kernel", "t1,t2,m0,b1,b1_phase,b0,inversion_efficiency,diffusion,velocity,bound_fraction,exchange_rate,t1_bound,pool_b_fraction,pool_b_exchange,t1_pool_b,t2_pool_b,pool_b_shift,duration,kind,flip,phase,action,output_index,shim_index,saturation,rf_frequency,profile,profile_index,lineshape,pairs,pair_index,pair_direction,grad_pair_value,grad_pair_tangent,dot_t1,dot_t2,dot_m0,dot_b1,dot_b1_phase,dot_b0,dot_inversion_efficiency,dot_diffusion,dot_velocity,dot_bound_fraction,dot_exchange_rate,dot_t1_bound,dot_pool_b_fraction,dot_pool_b_exchange,dot_t1_pool_b,dot_t2_pool_b,dot_pool_b_shift,dot_duration,dot_flip,dot_phase,duration_row,pool_table,pool_bars,pool_durations,row_count,grad_output_real,grad_output_imag,grad_tissue_value,grad_tissue_tangent,grad_flip_value,grad_flip_tangent,grad_phase_value,grad_phase_tangent,grad_duration_value,grad_duration_tangent,trajectory_vr,trajectory_vi,trajectory_tr,trajectory_ti,problem_base,problem_end,atom_count,train_count,event_count,output_count,flow_scale,washout_scale,profile_step,lineshape_step,state_count,single_train,atom_stride,shim_rows,shimmed,locations,profiled,profile_bins,dynamic,directed,off_axis,moving,diffusing,transmit,density,inverting,broadened,lineshape_bins,pools,narrow,tabulated,recording,block_states,problems", "ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppippppppppppppppiiiiiiffffiiiiiiiiiiiiiiiiiiiiiiii", 105, 106, -1, BLOCHSIM_LANES__epg_vjp_jvp_kernel},
    {"_epg_real_vjp_jvp_kernel", "t1,t2,m0,b1,inversion_efficiency,diffusion,duration,kind,flip,action,output_index,shim_index,dot_t1,dot_t2,dot_m0,dot_b1,dot_inversion_efficiency,dot_diffusion,dot_duration,dot_flip,grad_output_imag,grad_tissue_value,grad_tissue_tangent,grad_flip_value,grad_flip_tangent,grad_duration_value,grad_duration_tangent,trajectory_value,trajectory_tangent,problem_base,problem_end,atom_count,train_count,event_count,output_count,state_count,single_train,atom_stride,shim_rows,shimmed,diffusing,transmit,density,inverting,block_states,problems", "pppppppppppppppppppppppppppppiiiiiiiiiiiiiiiii", 44, 45, -1, BLOCHSIM_LANES__epg_real_vjp_jvp_kernel},
    {"_epg_real_vjp_kernel", "t1,t2,m0,b1,inversion_efficiency,diffusion,duration,kind,flip,action,output_index,shim_index,grad_output_imag,grad_tissue,grad_flip,grad_duration,trajectory_value,problem_base,problem_end,atom_count,train_count,event_count,output_count,state_count,single_train,atom_stride,shim_rows,shimmed,diffusing,transmit,density,inverting,block_states,problems", "pppppppppppppppppiiiiiiiiiiiiiiiii", 32, 33, -1, BLOCHSIM_LANES__epg_real_vjp_kernel},
    {"_epg_real_kernel", "t1,t2,m0,b1,inversion_efficiency,diffusion,duration,kind,flip,action,output_index,shim_index,output_real,output_imag,atom_count,train_count,event_count,output_count,state_count,single_train,atom_stride,shimmed,diffusing,transmit,density,inverting,block_states,problems", "ppppppppppppppiiiiiiiiiiiiii", 26, 27, -1, BLOCHSIM_LANES__epg_real_kernel},
    {"_epg_real_jvp_kernel", "t1,t2,m0,b1,inversion_efficiency,diffusion,duration,kind,flip,action,output_index,shim_index,tangent_t1,tangent_t2,tangent_m0,tangent_b1,tangent_inversion_efficiency,tangent_diffusion,tangent_duration,tangent_flip,output_real,output_imag,atom_count,train_count,event_count,output_count,state_count,single_train,atom_stride,shimmed,diffusing,transmit,density,inverting,block_states,problems", "ppppppppppppppppppppppiiiiiiiiiiiiii", 34, 35, -1, BLOCHSIM_LANES__epg_real_jvp_kernel},
    {"_epg_kernel", "t1,t2,m0,b1,b1_phase,b0,inversion_efficiency,diffusion,velocity,bound_fraction,bound_exchange,t1_bound,pool_b_fraction,pool_b_exchange,t1_pool_b,t2_pool_b,pool_b_shift,duration,kind,flip,phase,phase_cos,phase_sin,action,output_index,shim_index,saturation,rf_frequency,profile,profile_index,lineshape,pairs,pair_index,duration_row,pool_table,output_real,output_imag,atom_count,train_count,event_count,output_count,flow_scale,washout_scale,profile_step,lineshape_step,state_count,single_train,atom_stride,shim_rows,shimmed,locations,profiled,profile_bins,dynamic,broadened,lineshape_bins,pools,narrow,tabulated,off_axis,moving,diffusing,transmit,density,inverting,block_states,problems", "pppppppppppppppppppppppppppppppppppppiiiiffffiiiiiiiiiiiiiiiiiiiiii", 65, 66, -1, BLOCHSIM_LANES__epg_kernel},
    {"_epg_jvp_kernel", "t1,t2,m0,b1,b1_phase,b0,inversion_efficiency,diffusion,velocity,bound_fraction,exchange_rate,t1_bound,pool_b_fraction,pool_b_exchange,t1_pool_b,t2_pool_b,pool_b_shift,duration,kind,flip,phase,action,output_index,shim_index,tangent_t1,tangent_t2,tangent_m0,tangent_b1,tangent_b1_phase,tangent_b0,tangent_inversion_efficiency,tangent_diffusion,tangent_velocity,tangent_bound_fraction,tangent_exchange_rate,tangent_t1_bound,tangent_pool_b_fraction,tangent_pool_b_exchange,tangent_t1_pool_b,tangent_t2_pool_b,tangent_pool_b_shift,tangent_duration,tangent_flip,tangent_phase,saturation,rf_frequency,profile,profile_index,lineshape,pairs,pair_index,pair_direction,duration_row,pool_table,output_real,output_imag,atom_count,train_count,event_count,output_count,flow_scale,washout_scale,profile_step,lineshape_step,state_count,single_train,atom_stride,shim_rows,shimmed,locations,profiled,profile_bins,dynamic,broadened,lineshape_bins,pools,narrow,tabulated,off_axis,moving,diffusing,transmit,density,inverting,block_states,problems", "ppppppppppppppppppppppppppppppppppppppppppppppppppppppppiiiiffffiiiiiiiiiiiiiiiiiiiiii", 84, 85, -1, BLOCHSIM_LANES__epg_jvp_kernel},
    {"_pooled_kernel", "m0,b1,b1_phase,b0,efficiency,diffusion,velocity,dm0,db1,db1_phase,db0,defficiency,ddiffusion,dvelocity,duration,kind,flip,phase,action,output_index,shim_index,saturation,rf_frequency,dduration,dflip,dphase,table,dtable,pool_index,profile,profile_index,lineshape,pairs,pair_index,dpairs,output_real,output_imag,trajectory,base,atom_count,event_count,output_count,state_count,rows,flow_scale,washout_scale,profile_step,lineshape_step,locations,profile_bins,lineshape_bins,n,m,blocks,planes,atom_stride,shimmed,profiled,dynamic,directed_pairs,directed_table,following,keep,off_axis,moving,diffusing,transmit,density,inverting,P,S", "ppppppppppppppppppppppppppppppppppppppiiiiiiffffiiiiiiiiiiiiiiiiiiiiiii", 70, 69, 69, BLOCHSIM_LANES__pooled_kernel},
    {"_pooled_adjoint_kernel", "m0,b1,b1_phase,b0,efficiency,diffusion,velocity,dm0,db1,db1_phase,db0,defficiency,ddiffusion,dvelocity,duration,kind,flip,phase,action,output_index,shim_index,saturation,rf_frequency,dduration,dflip,dphase,table,dtable,pool_index,profile,profile_index,lineshape,pairs,pair_index,dpairs,grad_real,grad_imag,grad_tissue,dgrad_tissue,grad_duration,dgrad_duration,grad_flip,dgrad_flip,grad_phase,dgrad_phase,grad_table,dgrad_table,grad_pairs,dgrad_pairs,trajectory,base,atom_count,event_count,output_count,state_count,rows,flow_scale,washout_scale,profile_step,lineshape_step,locations,profile_bins,lineshape_bins,m0_row,b1_row,b1_phase_row,b0_row,efficiency_row,diffusion_row,velocity_row,n,m,blocks,planes,atom_stride,shimmed,profiled,dynamic,directed_pairs,directed_table,following,off_axis,moving,diffusing,transmit,density,inverting,P,S", "ppppppppppppppppppppppppppppppppppppppppppppppppppiiiiiiffffiiiiiiiiiiiiiiiiiiiiiiiiiiiii", 88, 87, 87, BLOCHSIM_LANES__pooled_adjoint_kernel},
    {"_regress_kernel", "signal,frequency,phase,feature_mean,weight,parameter_mean,output,voxels,contrasts,features,parameters,scale,splits,threads", "pppppppiiiifii", 13, -1, -1, BLOCHSIM_LANES__regress_kernel},
    {"_regress_vjp_kernel", "signal,frequency,phase,weight,cotangent,output,voxels,contrasts,features,parameters,scale,splits,threads", "ppppppiiiifii", 12, -1, -1, BLOCHSIM_LANES__regress_vjp_kernel},
};

#define BLOCHSIM_FOR_EACH_KERNEL(X) \
    X(_three_pool_table_jvp_kernel) \
    X(_three_pool_table_kernel) \
    X(_epg_vjp_kernel) \
    X(_epg_vjp_jvp_kernel) \
    X(_epg_real_vjp_jvp_kernel) \
    X(_epg_real_vjp_kernel) \
    X(_epg_real_kernel) \
    X(_epg_real_jvp_kernel) \
    X(_epg_kernel) \
    X(_epg_jvp_kernel) \
    X(_pooled_kernel) \
    X(_pooled_adjoint_kernel) \
    X(_regress_kernel) \
    X(_regress_vjp_kernel)

}  // namespace bsk
