"""What ``real_subspace_axis`` accepts from a stream no builder wrote.

The predicate is contracted against the sequences the builders produce, and it
reads only phases, off-resonance, transmit phase and velocity. An
autogenerated stream reaches the kernels without a builder and can say things
no builder says -- pulses of either role in any order, dephasing anywhere or
nowhere at all. A train that never dephases keeps every configuration at order
zero, which is the shape a random mix essentially never produces and so the
one worth generating deliberately.

The real kernels are an optimization, not an approximation, so every stream
the predicate admits has to give what the complex kernels give.
"""

from __future__ import annotations

import pytest
import torch

from blochsim.sequence._accelerators import _run_packed, real_subspace_axis
from blochsim.sequence._simulation import TissueProperties, _prepare_tissue

VOXELS = 32
STATES = 8
TRAINS = 40

RF, ADC = 1, 2
CRUSH_BEFORE, CRUSH_AFTER, SPOIL_AFTER, SHIFT_AFTER = 1, 2, 8, 16
RECORD, EXCITATION, REFOCUSING = 32, 64, 128
DEPHASING = (CRUSH_BEFORE, CRUSH_AFTER, SPOIL_AFTER, SHIFT_AFTER)


def _tissue(device: str) -> tuple[torch.Tensor, ...]:
    prepared, _, _ = _prepare_tissue(
        TissueProperties(
            t1_ms=torch.linspace(600.0, 1400.0, VOXELS),
            t2_ms=torch.linspace(40.0, 120.0, VOXELS),
        ),
        device,
    )
    return tuple(value.to(torch.float32).contiguous() for value in prepared)


def _chance(rng: torch.Generator, odds: float) -> bool:
    return bool(torch.rand(1, generator=rng).item() < odds)


def _stream(
    rng: torch.Generator, device: str, *, still: bool
) -> tuple[tuple[torch.Tensor, ...], int] | None:
    """One hand-assembled event stream, or ``None`` if it records nothing.

    Every pulse shares one phase, because the predicate refuses a stream whose
    roles disagree about it and this is looking at what it accepts.
    """
    count = int(torch.randint(3, 10, (1,), generator=rng).item())
    phase = float(torch.rand(1, generator=rng).item()) * torch.pi
    kinds, flips, actions, phases, durations, outputs = [], [], [], [], [], []
    recorded = 0
    for index in range(count):
        # An excitation first, so the stream always carries both roles.
        role = EXCITATION if index == 0 or _chance(rng, 0.25) else REFOCUSING
        dephasing = 0
        if not still:
            for bit in DEPHASING:
                if _chance(rng, 0.4):
                    dephasing |= bit
        kinds.append(RF)
        flips.append(float(torch.rand(1, generator=rng).item()) * torch.pi)
        actions.append(role | dephasing)
        phases.append(phase)
        durations.append(2e-3 + 6e-3 * float(torch.rand(1, generator=rng).item()))
        outputs.append(0)
        if _chance(rng, 0.7):
            shifted = 0 if still else (SHIFT_AFTER if _chance(rng, 0.5) else 0)
            kinds.append(ADC)
            flips.append(0.0)
            actions.append(RECORD | shifted)
            phases.append(phase)
            durations.append(2e-3)
            outputs.append(recorded)
            recorded += 1
    if recorded == 0:
        return None
    events = (
        torch.tensor(durations, dtype=torch.float32, device=device),
        torch.tensor(kinds, dtype=torch.int32, device=device),
        torch.tensor(flips, dtype=torch.float32, device=device),
        torch.tensor(phases, dtype=torch.float32, device=device),
        torch.tensor(actions, dtype=torch.uint8, device=device),
        torch.tensor(outputs, dtype=torch.int32, device=device),
        torch.zeros(len(kinds), dtype=torch.int32, device=device),
        torch.zeros(len(kinds), dtype=torch.float32, device=device),
        torch.zeros(len(kinds), dtype=torch.float32, device=device),
    )
    return events, recorded


def _backends() -> list[str]:
    return ["host"] + (["cuda"] if torch.cuda.is_available() else [])


def _pair(backend: str, tissue, events, recorded):
    """Return the complex and real signals from the backend named.

    Each entry point is called directly rather than routed. A stream this
    small sits below the threshold that decides whether a device run is worth
    leaving the host for, so routing it would hand the CUDA case to the C++
    kernels and quietly test them twice.
    """
    if backend == "host":
        shape = (tissue, events, STATES, recorded)
        return _run_packed(*shape, 1), _run_packed(*shape, 1, real_axis=1)
    from blochsim.sequence import _epg_triton

    shape = dict(state_count=STATES, output_count=recorded)
    return (
        _epg_triton.simulate(tissue, events, **shape),
        _epg_triton.simulate(tissue, events, real_axis=1, **shape),
    )


@pytest.mark.parametrize("backend", _backends())
@pytest.mark.parametrize("still", [False, True], ids=["dephasing", "never-dephasing"])
def test_every_stream_the_verdict_admits_gives_the_complex_answer(
    backend: str, still: bool
) -> None:
    """The real kernels are an optimization, so what the verdict admits agrees."""
    device = "cpu" if backend == "host" else "cuda"
    tissue = _tissue(device)
    rng = torch.Generator().manual_seed(0)
    admitted = 0
    worst = 0.0
    for _ in range(TRAINS):
        built = _stream(rng, device, still=still)
        if built is None:
            continue
        events, recorded = built
        if real_subspace_axis(events, tissue) != 1:
            continue
        admitted += 1
        complex_signal, real_signal = _pair(backend, tissue, events, recorded)
        scale = float(complex_signal.abs().max())
        if scale < 1e-9:
            continue
        worst = max(worst, float((complex_signal - real_signal).abs().max()) / scale)
    # A run that admitted nothing would pass without comparing anything.
    assert admitted > TRAINS // 2, f"only {admitted} of {TRAINS} streams admitted"
    assert worst < 1e-5, f"worst gap {worst:.3e} over {admitted} streams"
