"""Which sequences the fused kernels answer for, which is all of them.

An event stream reaches the kernels through ``_pack_events``, which carries
timing, flip angle, phase and a per-event action word. The action word is read
off the description like everything else, so a description assembled by hand
-- or arriving from a scanner -- runs exactly as well as one a builder wrote.
"""

import pytest
import torch

from blochsim.sequence import (
    EpgEngine,
    TissueProperties,
    fse_description,
)
from blochsim.sequence._description import RfUse

ECHOES = 8
STATES = 10


def _describe():
    return fse_description(
        torch.deg2rad(torch.full((ECHOES,), 140.0)),
        echo_spacing_s=5e-3,
        phases_rad=torch.pi / 2,
    )


def _tissue():
    return TissueProperties(
        t1_ms=torch.tensor([800.0, 1400.0]), t2_ms=torch.tensor([45.0, 120.0])
    )


def _reference(description, tissue, state_count: int = STATES):
    """The same train through the state machine written out in torch."""
    from blochsim.sequence._accelerators import _pack_events, geometry_of
    from blochsim.sequence._simulation import _prepare_tissue
    from utils.packed_reference import simulate_packed

    prepared, shape, device = _prepare_tissue(tissue, "cpu")
    packed = _pack_events(
        description,
        repetitions=1,
        record="all",
        device=device,
        rf_raster_time_s=1e-6,
    )
    events = (
        packed.duration,
        packed.kind,
        packed.flip,
        packed.phase,
        packed.action,
        packed.output_index,
        packed.shim_index,
        packed.saturation,
        packed.rf_frequency_hz,
    )
    signal = simulate_packed(
        tuple(value.to(torch.float32).contiguous() for value in prepared),
        events,
        state_count=state_count,
        output_count=int(packed.output_count),
        geometry=geometry_of(description),
    )
    return signal.reshape(*shape, int(packed.output_count))


def test_a_builder_description_matches_the_state_machine_written_out():
    """The whole route -- description, preparation, packing, kernel -- against
    a reference that shares none of it.
    """
    fused = EpgEngine().simulate(_describe(), _tissue(), nstates=STATES).signal
    reference = _reference(_describe(), _tissue())

    scale = reference.abs().max()
    assert scale > 0.0
    assert ((reference - fused).abs().max() / scale) < 1e-5


# --- a sequence no builder wrote ---


def _handmade():
    """A refocused train written out by hand, saying what it plays.

    This is the shape an autogenerated description arrives in, and the point
    of carrying the action word is that it reaches the kernels anyway.
    """
    from blochsim.sequence import EventAction, ideal_rf_definition
    from blochsim.sequence._description import (
        AdcRole,
        SequenceDescription,
        SequenceEvent,
    )

    events = [SequenceEvent.rf(0.0, 0, RfUse.EXCITATION, torch.pi / 2, torch.pi / 2)]
    for index in range(ECHOES):
        centre = 5e3 * (index + 1)
        events.append(
            SequenceEvent.rf(
                centre - 2.5e3,
                0,
                RfUse.REFOCUSING,
                torch.deg2rad(torch.tensor(140.0)),
                torch.pi / 2,
                action=EventAction.CRUSH_BEFORE | EventAction.CRUSH_AFTER,
            )
        )
        events.append(
            SequenceEvent.adc(centre, AdcRole.ECHO_CENTER, torch.pi / 2, is_echo=True)
        )
    return SequenceDescription(
        subsequence_index=0,
        tr_duration_us=5e3 * (ECHOES + 1),
        events=tuple(events),
        rf_definitions={0: ideal_rf_definition()},
    )


def test_a_hand_written_sequence_reaches_the_kernels():
    """The payoff: the description says what it plays, so the engine -- which
    knows nothing at all -- packs it straight onto the fused kernels.
    """
    fused = EpgEngine().simulate(_handmade(), _tissue(), nstates=STATES).signal
    reference = _reference(_handmade(), _tissue())

    scale = reference.abs().max()
    assert scale > 0.0
    assert ((reference - fused).abs().max() / scale) < 1e-5


def test_the_crushers_are_what_the_description_says():
    """Strip the action off every event and the engine must record a different
    train -- otherwise the action word is not what is being read.
    """
    from dataclasses import replace

    from blochsim.sequence import EventAction

    described = _handmade()
    bare = replace(
        described,
        events=tuple(
            replace(event, action=EventAction.NONE) for event in described.events
        ),
    )

    crushed = EpgEngine().simulate(described, _tissue(), nstates=STATES).signal
    plain = EpgEngine().simulate(bare, _tissue(), nstates=STATES).signal

    assert crushed.abs().max() > 0.0
    assert (crushed - plain).abs().max() > 1e-3 * crushed.abs().max()


def test_the_state_matrix_is_sized_from_what_the_sequence_winds():
    """Two crushers per refocusing pulse, counted off the description."""
    assert EpgEngine().shifts_per_repetition(_handmade()) == 2 * ECHOES


def test_a_tissue_no_kernel_can_take_says_so():
    """With one route there is no fallback, so an unreachable device raises
    rather than quietly running somewhere else.
    """
    from blochsim.sequence import _accelerators

    original = _accelerators._backend_available
    _accelerators._backend_available = lambda device: False
    try:
        with pytest.raises(RuntimeError, match="no fused EPG kernel"):
            EpgEngine().simulate(_handmade(), _tissue(), nstates=STATES)
    finally:
        _accelerators._backend_available = original
